<!DOCTYPE html>
<html>
<head>
    
    
</head>
<body>
	<?php echo form_open('clientes/atualizar', 'id="form-clientes"'); ?>
 
	<input type="hidden" name="id_cliente" value="<?php echo $dados_cliente[0]->id_cliente; ?>"/>
 	<div class="row">
        <div class="form-group col-md-5">
			<label for="nome">Nome:</label><br/>
			<input type="text" class="form-control" name="nome"	value="<?php echo $dados_cliente[0]->nome; ?>"/>
			<div class="error"><?php echo form_error('cnome'); ?></div>
		</div> 	
		<div class="form-group col-md-5">
			<label for="nome">CPF:</label><br/>
			<input type="text" class="form-control" name="cpf" 	value="<?php echo $dados_cliente[0]->cpf; ?>"/>
			<div class="error"><?php echo form_error('cpf'); ?></div>
		</div> 	
	</div>

	<div class="row">
        <div class="form-group col-md-5">
			<label for="nome">Telefone:</label><br/>
			<input type="text" class="form-control" name="telefone" value="<?php echo $dados_cliente[0]->telefone; ?>"/>
			<div class="error"><?php echo form_error('telefone'); ?></div>
		</div>
		<div class="form-group col-md-5">
			<label for="responsavel">Responsavel:</label><br/>
			<input type="text" class="form-control" name="responsavel" value="<?php echo $dados_cliente[0]->responsavel; ?>"/>
			<div class="error"><?php echo form_error('responsavel'); ?></div>
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="cep">CEP:</label><br/>
			<input type="text" class="form-control" name="cep" value="<?php echo $dados_cliente[0]->cep; ?>"/>
			<div class="error"><?php echo form_error('cep'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="cidade">Cidade:</label><br/>
			<input type="text" class="form-control" name="cidade" value="<?php echo $dados_cliente[0]->cidade; ?>"/>
			<div class="error"><?php echo form_error('cidade'); ?></div>
		</div> 
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="rua">Rua:</label><br/>
			<input type="text" class="form-control" name="rua" value="<?php echo $dados_cliente[0]->rua; ?>"/>
			<div class="error"><?php echo form_error('rua'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="bairro">Bairro:</label><br/>
			<input type="text" class="form-control" name="bairro" value="<?php echo $dados_cliente[0]->bairro; ?>"/>
			<div class="error"><?php echo form_error('bairro'); ?></div>
		</div> 
	</div>


 	<div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
        </div>
    </div>
 
	<?php echo form_close(); ?>
</body>
</html>