<!DOCTYPE html>
<html>
<head>
    
    
</head>
<body>
	<?php echo form_open('demografico/atualizar', 'id="form-demografico"'); ?>
 
	<input type="hidden" name="id_questionario_demografico" value="<?php echo $dados_demografico[0]->id_questionario_demografico; ?>"/>
 	<div class="row">
        <div class="form-group col-md-5">
			<label for="nome_usuario">nome_usuario:</label><br/>
			<input type="text" class="form-control" name="nome_usuario"	value="<?php echo $dados_demografico[0]->nome_respondente; ?>"/>
			<div class="error"><?php echo form_error('nome_respondente'); ?></div>
		</div> 	
		<div class="form-group col-md-5">
			<label for="idade_respondente">idade_respondente:</label><br/>
			<input type="text" class="form-control" name="idade_respondente" 	value="<?php echo $dados_demografico[0]->idade_respondente; ?>"/>
			<div class="error"><?php echo form_error('idade_respondente'); ?></div>
		</div> 	
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="ec_respondente">Sexo:</label><br/>
			<input type="text" class="form-control" name="ec_respondente" value="<?php echo $dados_demografico[0]->ec_respondente; ?>"/>
			<div class="error"><?php echo form_error('ec_respondente'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="ec_respondente">Estado Civil:</label><br/>
			<input type="text" class="form-control" name="ec_respondente" value="<?php echo $dados_demografico[0]->ec_respondente; ?>"/>
			<div class="error"><?php echo form_error('ec_respondente'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="cidade_respondente">Cidade:</label><br/>
			<input type="text" class="form-control" name="ec_rescidade_respondentepondente" value="<?php echo $dados_demografico[0]->cidade_respondente; ?>"/>
			<div class="error"><?php echo form_error('cidade_respondente'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="ec_respondente">Escolaridade:</label><br/>
			<input type="text" class="form-control" name="ec_respondente" value="<?php echo $dados_demografico[0]->ec_respondente; ?>"/>
			<div class="error"><?php echo form_error('ec_respondente'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="cidade_respondente">Cidade:</label><br/>
			<input type="text" class="form-control" name="ec_rescidade_respondentepondente" value="<?php echo $dados_demografico[0]->cidade_respondente; ?>"/>
			<div class="error"><?php echo form_error('cidade_respondente'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="ec_respondente">Escolaridade:</label><br/>
			<input type="text" class="form-control" name="ec_respondente" value="<?php echo $dados_demografico[0]->ec_respondente; ?>"/>
			<div class="error"><?php echo form_error('ec_respondente'); ?></div>
		</div> 
	</div>

    
    <div class="row">
		<div class="form-group col-md-5">
			<label for="qtd_automoveis">qtd_automoveis:</label><br/>
			<input type="text" class="form-control" name="qtd_automoveis" value="<?php echo $dados_demografico[0]->qtd_automoveis; ?>"/>
			<div class="error"><?php echo form_error('qtd_automoveis'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="qtd_empregados">qtd_empregados:</label><br/>
			<input type="text" class="form-control" name="qtd_empregados" value="<?php echo $dados_demografico[0]->qtd_empregados; ?>"/>
			<div class="error"><?php echo form_error('qtd_empregados'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="qtd_maquina_lavar">qtd_maquina_lavar:</label><br/>
			<input type="text" class="form-control" name="qtd_maquina_lavar" value="<?php echo $dados_demografico[0]->qtd_maquina_lavar; ?>"/>
			<div class="error"><?php echo form_error('qtd_maquina_lavar'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="qtd_banheiros">qtd_banheiros:</label><br/>
			<input type="text" class="form-control" name="qtd_banheiros" value="<?php echo $dados_demografico[0]->qtd_banheiro; ?>"/>
			<div class="error"><?php echo form_error('qtd_banheiros'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="qtd_dvd">qtd_dvd:</label><br/>
			<input type="text" class="form-control" name="qtd_dvd" value="<?php echo $dados_demografico[0]->qtd_dvd; ?>"/>
			<div class="error"><?php echo form_error('qtd_dvd'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="qtd_geladeira">qtd_geladeira:</label><br/>
			<input type="text" class="form-control" name="qtd_geladeira" value="<?php echo $dados_demografico[0]->qtd_geladeira; ?>"/>
			<div class="error"><?php echo form_error('qtd_geladeira'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="qtd_freezer">qtd_freezer:</label><br/>
			<input type="text" class="form-control" name="qtd_freezer" value="<?php echo $dados_demografico[0]->qtd_freezer; ?>"/>
			<div class="error"><?php echo form_error('qtd_freezer'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="qtd_pc">qtd_pc:</label><br/>
			<input type="text" class="form-control" name="qtd_pc" value="<?php echo $dados_demografico[0]->qtd_pc; ?>"/>
			<div class="error"><?php echo form_error('qtd_pc'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="qtd_lava">qtd_lava:</label><br/>
			<input type="text" class="form-control" name="qtd_lava" value="<?php echo $dados_demografico[0]->qtd_lava; ?>"/>
			<div class="error"><?php echo form_error('qtd_lava'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="qtd_micro">qtd_micro:</label><br/>
			<input type="text" class="form-control" name="qtd_micro" value="<?php echo $dados_demografico[0]->qtd_micro; ?>"/>
			<div class="error"><?php echo form_error('qtd_micro'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="qtd_lava">qtd_moto:</label><br/>
			<input type="text" class="form-control" name="qtd_moto" value="<?php echo $dados_demografico[0]->qtd_moto; ?>"/>
			<div class="error"><?php echo form_error('qtd_moto'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="qtd_secadora">qtd_secadora:</label><br/>
			<input type="text" class="form-control" name="qtd_secadora" value="<?php echo $dados_demografico[0]->qtd_secadora; ?>"/>
			<div class="error"><?php echo form_error('qtd_secadora'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="origem_agua">origem_agua:</label><br/>
			<input type="text" class="form-control" name="origem_agua" value="<?php echo $dados_demografico[0]->origem_agua; ?>"/>
			<div class="error"><?php echo form_error('origem_agua'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="tipo_rua">tipo_rua:</label><br/>
			<input type="text" class="form-control" name="tipo_rua" value="<?php echo $dados_demografico[0]->tipo_rua; ?>"/>
			<div class="error"><?php echo form_error('tipo_rua'); ?></div>
		</div> 
	</div>

    <div class="row">
		<div class="form-group col-md-5">
			<label for="renda">renda:</label><br/>
			<input type="text" class="form-control" name="renda" value="<?php echo $dados_demografico[0]->renda; ?>"/>
			<div class="error"><?php echo form_error('renda'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="escolaridade_chefe">escolaridade_chefe:</label><br/>
			<input type="text" class="form-control" name="escolaridade_chefe" value="<?php echo $dados_demografico[0]->escolaridade_chefe; ?>"/>
			<div class="error"><?php echo form_error('escolaridade_chefe'); ?></div>
		</div> 
	</div>

 	<div class="row">
        <div class="col-md-12">
                <a onClick="history.go(-1)" class="btn btn-default">Voltar</a>
        </div>
    </div>
 
	<?php echo form_close(); ?>
</body>
</html>
