<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
</head>

<body>
<?php echo form_open('demograficos/inserir', 'id="form-demografico"'); ?>
			<div class="row">
				<div class="col-md-10">
					<br><br><br>
           <h2 style="font-size: 16px">Olá você está convidado a participar de um estudo que avalia a saúde mental nas universidades .....
					 Sua participação será voluntária e consiste em responder algumas perguntas sobre você, sua vida acadêmica e sobre sintomas de ansiedade, 
					 estresse e depressão. Ao final de suas respostas você recebera o seu escore bem como orientações sobre o que pode ajudar se você tiver
					  sintomas consideráveis de estresse, ansiedade ou depressão autorrelatados. O retorno não trata-se de um diagnóstico, pois este só pode 
						ser feito por um profissional da saúde mental, é apenas a compilação das suas respostas.<br><br><br></h2>

					 <h1 style="font-size: 18px" >Dados Pessoais<br></h1>
        </div>
    	</div>
    
    <form action="" method="post" ENCTYPE="multipart/form-data">
      <div class="row">
        <div class="form-group col-md-5">
            <label for="nome_respondente">Nome</label> 
            <input type="text" class="form-control" id="nome_respondente" name="nome_respondente"
                placeholder="Informe o seu Nome" required
                value="<?php echo isset($view_nome_respondente) ? $view_nome_respondente: '' ; ?>">
        </div>     
        <div class="form-group col-md-5">
            <label for="idade_respondente">Idade</label> 
            <input type="text" class="form-control" id="idade_respondente" name="idade_respondente"
                placeholder="informe sua idade" required
                value="<?php echo isset($view_idade_respondente) ? $view_idade_respondente: '' ; ?>">
        </div>
    	</div>
 
      <div class="row">
			  <div class="form-group col-md-5">
            <label for="sexo_respondente">Sexo</label> 
						<select class="custom-select" id="sexo_select">
							<option selected value="1">Feminino</option>
							<option value="2">Masculino</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="ec_respondente">Estado Civil</label> 
						<select class="custom-select" id="ec_select">
							<option selected value="1">Solteiro</option>
							<option value="2">Casado</option>
							<option value="3">Viuvo</option>
							<option value="4">Separado</option>
						</select>
        </div>
    	</div>
			<div class="row">
				<div class="form-group col-md-5">
            <label for="cidade_respondente">Cidade</label> 
            <input type="text" class="form-control" id="cidade_respondente" name="cidade_respondente"
                placeholder="cidade" required
                value="<?php echo isset($view_cidade_respondente) ? $view_cidade_respondente: '' ; ?>">
        </div>
        <div class="form-group col-md-5">
            <label for="escolaridade_respondente">Escolaridade</label> 
            <select class="custom-select" id="escolaridade_select">
							<option selected value="1">Ensino Fundamental Completo ou Incompleto </option>
							<option value="2">Ensino Médio Incompleto</option>
							<option value="3">Ensino Superior Incompleto</option>
							<option value="4">Ensino Superior Completo</option>
							<option value="5">Pós-Graduação</option>
							<option value="6">Mestrado</option>
							<option value="7">Doutorado</option>
						</select>
        </div>
    	</div>

			<div class="row">
				<div class="col-md-10">
					<br><br><br>
           <h2 style="font-size: 16px">Agora vou fazer algumas perguntas sobre itens do domicilio para efeito de classificação econômica. 
					 Todos os itens de eletroeletrônicos que vou citar devem estar funcionando, incluindo os que estão guardados. 
					 Caso não estejam funcionando, considere apenas se tiver intenção de consertar ou repor nos próximos seis meses.
					 Vamos começar? No domicílio tem (LEIA CADA ITEM)<br><br><br></h2>

					 <h1 style="font-size: 18px" >Itens de Conforto<br></h1>
        </div>
    	</div>

			<div class="row">
			  <div class="form-group col-md-5">
            <label for="automoveis">Quantidade de automoveis de passeio, de uso exclusivamente particular</label> 
						<select class="custom-select" id="qtd_automoveis">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="empregados">Quantidade de empregados mensalitas, que trabalham pelo menos 5dias na semana</label> 
						<select class="custom-select" id="qtd_empregados">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
    	</div>

			<div class="row">
			  <div class="form-group col-md-5">
            <label for="qtd_maquina_lavar">Quantidade de maquinas de lavar, excluindo tanquinho</label> 
						<select class="custom-select" id="qtd_maquina_lavar">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="qtd_banheiro">Quantidade banheiros</label> 
						<select class="custom-select" id="qtd_banheiro">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
    	</div>

			<div class="row">
			  <div class="form-group col-md-5">
            <label for="qtd_dvd">DVD, incluindo qualquer dispositivo que leia DVD e desconsiderando DVD de automoveis</label> 
						<select class="custom-select" id="qtd_dvd">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="qtd_geladeira">Quantidade de Geladeiras</label> 
						<select class="custom-select" id="qtd_geladeira">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
    	</div>

			<div class="row">
			  <div class="form-group col-md-5">
            <label for="qtd_freezer">Quantidade de freezers independentes ou parte da geladeira duplex</label> 
						<select class="custom-select" id="qtd_freezer">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="qtd_pc">Quantidade de Microcomputadores considerando PC's e noteboks</label> 
						<select class="custom-select" id="qtd_pc">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
    	</div>

			<div class="row">
			  <div class="form-group col-md-5">
            <label for="qtd_lava">Quantidade de lava louças</label> 
						<select class="custom-select" id="qtd_lava">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="qtd_micro">Quantidade de Micro-ondas</label> 
						<select class="custom-select" id="qtd_micro">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
    	</div>

			<div class="row">
				<div class="form-group col-md-5">
            <label for="qtd_moto">Quantidade de motoclicletas de passeio, de uso exclusivamente particular</label> 
						<select class="custom-select" id="qtd_moto">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="qtd_secadora">Quantidade maquinas secadora de roupas, considerando lava e seca </label> 
						<select class="custom-select" id="qtd_secadora">
							<option selected value="1">Não possui</option>
							<option value="2">1</option>
							<option value="3">2</option>
							<option value="4">3</option>
							<option value="5">4+</option>
						</select>
        </div>
    	</div>

			<div class="row">
				<div class="col-md-10">
					<br><br><br>
					 <h1 style="font-size: 18px" >Abastecimento de agua<br></h1>
        </div>
    	</div>

			<div class="row">
			  <div class="form-group col-md-5">
            <label for="origem_agua">A agua utilizada neste domicilio é proveniente de ?</label> 
						<select class="custom-select" id="origem_agua">
							<option selected value="1">Rede geral de distribuição</option>
							<option value="2">Poço ou Nascente</option>
							<option value="3">Outro Meio</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="tipo_rua">considerando o trecho da rua do seu domicilio, voce diria que a rua é:</label> 
						<select class="custom-select" id="tipo_rua">
							<option selected value="1">Asfaltada/Pavimentada</option>
							<option value="2">Terra/Cascalho</option>
						</select>
        </div>
    	</div>

			<div class="row">
				<div class="col-md-10">
					<br><br><br>
					 <h1 style="font-size: 18px" >Renda Familiar<br></h1>
        </div>
    	</div>

			<div class="row">
			  <div class="form-group col-md-5">
            <label for="renda">Marque a opção que mais se adequa a sua renda familiar</label> 
						<select class="custom-select" id="renda">
							<option selected value="1">Até 2 salários minimos</option>
							<option value="2">2 a 4salários minimos</option>
							<option value="3">4 a 10 salários minimos</option>
							<option value="4">10 a 20 salários minimos</option>
							<option value="5">20+ salários minimos</option>
						</select>
        </div>
				<div class="form-group col-md-5">
            <label for="tipo_rua">Qual é o grau de instrução do chefe da família? Considere como chefe da família a pessoa que contribui como a 
								maior parte da renda do domicílio:</label> 
						<select class="custom-select" id="escolaridade_chefe_select">
							<option selected value="1">Ensino Fundamental Completo ou Incompleto </option>
							<option value="2">Ensino Médio Incompleto</option>
							<option value="3">Ensino Superior Incompleto</option>
							<option value="4">Ensino Superior Completo</option>
							<option value="5">Pós-Graduação</option>
							<option value="6">Mestrado</option>
							<option value="7">Doutorado</option>
						</select>
        </div>
    	</div>


			<div class="row">
				<div class="col-md-12">
						<input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
								<a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
				</div>

    <?php echo form_close(); ?>

</body>
</html>
