<!DOCTYPE html>
<html>
<head>
    
    
</head>
<body>
	<?php echo form_open('formularios/atualizar', 'id="form-formularios"'); ?>
 
	<input type="hidden" name="id_formulario" value="<?php echo $dados_formulario[0]->id_formulario; ?>"/>
 	<div class="row">
        <div class="form-group col-md-5">
			<label for="titulo">Titulo:</label><br/>
			<input type="text" class="form-control" name="titulo"	value="<?php echo $dados_formulario[0]->titulo; ?>"/>
			<div class="error"><?php echo form_error('titulo'); ?></div>
		</div> 	
		<div class="form-group col-md-5">
			<label for="descricao">Descrição:</label><br/>
			<input type="text" class="form-control" name="descricao" 	value="<?php echo $dados_formulario[0]->descricao; ?>"/>
			<div class="error"><?php echo form_error('descricao'); ?></div>
		</div> 	
	</div>

	<div class="row">
        <div class="form-group col-md-5">
			<label for="conteudo">Conteudo:</label><br/>
			<input type="text" class="form-control" name="conteudo" value="<?php echo $dados_formulario[0]->conteudo; ?>"/>
			<div class="error"><?php echo form_error('conteudo'); ?></div>
		</div>
	</div>

 	<div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
        </div>
    </div>
	
	<?php echo form_close(); ?>
</body>
</html>