<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">

</head>

<body>
  
	<div class="col-sm-1">
    <a title="newForm" class="btn btn-primary btn-sm " href="<?php echo base_url() . 'formularios/novo_formulario/'; ?>"> <span>Cadastrar Formulario</span> </a>  
	</div>

	<div id="list" class="row">
		<div class="table-responsive col-md-12">
			<table class="table table-striped" cellspacing="30" cellpadding="30" id="formularios">
				<thead>
					<tr>
						<th>ID</th>
						<th>titulo</th>
						<th>Descricção</th>
						<th class="actions">Ações</th>
					</tr>
				</thead>
				
				<tbody>

					<?php foreach ( $formulario as $formulario ) {?>
						<tr>
							<td><?php echo $formulario->id_formulario; ?></td> 
							<td><?php echo $formulario->titulo; ?></td>    
							<td><?php echo $formulario->descricao; ?></td>
							<td class="actions">
                <a title="Editar" class="btn btn-warning btn-sm fa fa-pencil-square-o"
                    href="<?php echo base_url() . 'formularios/editar/' . $formulario->id_formulario; ?>"></a>
                <a title="Deletar" class="btn btn-danger btn-sm fa fa-trash" 
                    href="<?php echo base_url() . 'formularios/deletar/' . $formulario->id_formulario; ?>" onclick="return confirm('Confirma a exclusço deste registro?')"></a>
							</td>		

						</tr>	 	 	  	
						  	
				 	<?php } ?>
				</tbody>
			</table>
			 <h4><?php echo $this->session->flashdata('mensagem');?></h4>
        <h4><?php echo $this->session->flashdata('mensagemErro');?></h4>
		</div>
	</div>	

    <div class="row">
      <div class="col-sm-10" >
        <?php echo $pagination; ?>
      </div>
    </div>

</body>


</html>