<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
</head>

<body>

<div class="row" >
  <form action="/ps/usuarios/search1" method="post">
    <div class="col-sm-8">
        <input name="search1" class="form-control" id="search1" type="text"   placeholder="Filtrar Cliente " >   
    </div>

    <div class="col-sm-1">
      <button class="btn btn-primary btn-sm pull-left" type="submit">Filtrar</button>
    </div>

  </form>
</div>
 
	<div class="col-sm-1">
		<a title="newUser" class="btn btn-primary btn-sm " data-toggle="modal" data-target="#new_cliente">Novo Usuario</a>
	</div>  

	<div id="list" class="row">
		<div class="table-responsive col-md-12">
			<table class="table table-striped" cellspacing="30" cellpadding="30" id="usuarios">
				<thead>
					<tr>
						<th>ID</th>
						<th>Username</th>
						<th>Cargo</th>
						<th>Ativo</th>
						<th class="actions">Ações</th>
					</tr>
				</thead>
				
				<tbody>

					<?php foreach ( $usuario as $user ) {?>
						<tr>
							<td><?php echo $user->id; ?></td> 
							<td><?php echo $user->username; ?></td>    
							<td><?php echo $user->cargo; ?></td>
							<td><?php echo $user->ativo; ?> </td>
							<td class="actions">
                <a title="Editar" class="btn btn-warning btn-sm fa fa-pencil-square-o"
                    href="<?php echo base_url() . 'usuarios/editar/' . $user->id; ?>"></a>
                <a title="Deletar" class="btn btn-danger btn-sm fa fa-trash" 
                    href="<?php echo base_url() . 'usuarios/deletar/' . $user->id; ?>" onclick="return confirm('Confirma a exclusão deste registro?')"></a>
							</td>		

						</tr>	 	 	  	
						  	
				 	<?php } ?>
				</tbody>
			</table>
			 <h4><?php echo $this->session->flashdata('mensagem');?></h4>
        <h4><?php echo $this->session->flashdata('mensagemErro');?></h4>
		</div>
	</div>	

    <div class="row">
      <div class="col-sm-10" >
        <?php echo $pagination; ?>
      </div>
    </div>

</body>

<!-- Modal de inserir cliente-->
<div class="modal fade" id="new_cliente" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog modal-lg" >
    <div class="modal-content">
      <div class="modal-header  bg-red">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel">Adicionar Usuario</h4>
      </div>
      <div class="modal-body">
       
  <?php echo form_open('usuarios/inserir', 'id="form-pessoas"'); ?>
    
    <form action="" method="post" ENCTYPE="multipart/form-data">
      <div class="row">
        <div class="form-group col-md-5">
            <label for="username">Username</label> 
            <input type="text" class="form-control" id="username" name="username"
                placeholder="informe o nome" required
                value="<?php echo isset($view_username) ? $view_username: '' ; ?>">
        </div>     
        <div class="form-group col-md-5">
            <label for="cargo">Cargo</label> 
            <input type="text" class="form-control" id="cargo" name="cargo"
                placeholder="informe o Cargo" required
                value="<?php echo isset($view_cargo) ? $view_cargo: '' ; ?>">
        </div>
    	</div>
    
     <div class="row">
        <div class="form-group col-md-5">
            <label for="ativo">Ativo</label> 
            <input type="text" class="form-control" id="ativo" name="ativo"
                placeholder="informe 1" required
                value="<?php echo isset($view_ativo) ? $view_ativo: '' ; ?>">
        </div>
        <div class="form-group col-md-5">
					<label for="password">Senha</label> 
					<input type="text" class="form-control" id="password" name="password"
							placeholder="informe a senha" required 
							value="<?php echo isset($view_password) ? $view_password : '' ; ?>">
        </div>
    	</div>

			<div class="row">
				<div class="form-group col-md-5">
						<label for="email">email</label> 
						<input type="text" class="form-control" id="email" name="email"
								placeholder="informe um email" required
								value="<?php echo isset($view_email) ? $view_email : '' ; ?>">
				</div>
				
			</div>
			<div class="row">
					<div class="col-md-12">
							<input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
									<a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
					</div>

    <?php echo form_close(); ?>

		</div>

      </div>
    </div>
  </div>
</div> <!-- /.modal -->

</html>
