<!DOCTYPE html>
<html>
<head>
    
    
</head>
<body>
	<?php echo form_open('usuarios/atualizar', 'id="form-usuarios"'); ?>
 
	<input type="hidden" name="id_usuario" value="<?php echo $dados_usuario[0]->id_usuario; ?>"/>
 	<div class="row">
        <div class="form-group col-md-5">
			<label for="nome_usuario">nome_usuario:</label><br/>
			<input type="text" class="form-control" name="nome_usuario"	value="<?php echo $dados_usuario[0]->nome_usuario; ?>"/>
			<div class="error"><?php echo form_error('nome_usuario'); ?></div>
		</div> 	
		<div class="form-group col-md-5">
			<label for="email_usuario">email:</label><br/>
			<input type="text" class="form-control" name="email_usuario" 	value="<?php echo $dados_usuario[0]->email_usuario; ?>"/>
			<div class="error"><?php echo form_error('email_usuario'); ?></div>
		</div> 	
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="password">Senha:</label><br/>
			<input type="text" class="form-control" name="password" value="<?php echo $dados_usuario[0]->password; ?>"/>
			<div class="error"><?php echo form_error('password'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="tipo_usuario">Tipo:</label><br/>
			<input type="text" class="form-control" name="tipo_usuario" value="<?php echo $dados_usuario[0]->tipo_usuario; ?>"/>
			<div class="error"><?php echo form_error('tipo_usuario'); ?></div>
		</div> 
	</div>

 	<div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
        </div>
    </div>
 
	<?php echo form_close(); ?>
</body>
</html>
