<!DOCTYPE html>
<html>
<head>
    
    
</head>
<body>
	<?php echo form_open('usuarios/atualizar', 'id="form-usuarios"'); ?>
 
	<input type="hidden" name="id" value="<?php echo $dados_usuario[0]->id; ?>"/>
 	<div class="row">
        <div class="form-group col-md-5">
			<label for="username">Username:</label><br/>
			<input type="text" class="form-control" name="username"	value="<?php echo $dados_usuario[0]->username; ?>"/>
			<div class="error"><?php echo form_error('username'); ?></div>
		</div> 	
		<div class="form-group col-md-5">
			<label for="email">email:</label><br/>
			<input type="text" class="form-control" name="email" 	value="<?php echo $dados_usuario[0]->email; ?>"/>
			<div class="error"><?php echo form_error('email'); ?></div>
		</div> 	
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="senha">Senha:</label><br/>
			<input type="text" class="form-control" name="senha" value="<?php echo $dados_usuario[0]->password; ?>"/>
			<div class="error"><?php echo form_error('senha'); ?></div>
		</div> 
		<div class="form-group col-md-5">
			<label for="ativo">Ativo:</label><br/>
			<input type="text" class="form-control" name="ativo" value="<?php echo $dados_usuario[0]->ativo; ?>"/>
			<div class="error"><?php echo form_error('ativo'); ?></div>
		</div> 
	</div>

	<div class="row">
		<div class="form-group col-md-5">
			<label for="cargo">Cargo:</label><br/>
			<input type="text" class="form-control" name="cargo" value="<?php echo $dados_usuario[0]->cargo; ?>"/>
			<div class="error"><?php echo form_error('cargo'); ?></div>
		</div> 
	</div>


 	<div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
        </div>
    </div>
 
	<?php echo form_close(); ?>
</body>
</html>
