<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
</head>

<body>

<div class="row" >
  <form action="/ps/usuarios/search1" method="post">
    <div class="col-sm-8">
        <input name="search1" class="form-control" id="search1" type="text"   placeholder="Filtrar Cliente " >   
    </div>

    <div class="col-sm-1">
      <button class="btn btn-primary btn-sm pull-left" type="submit">Filtrar</button>
    </div>

  </form>
</div>
 
	<div class="col-sm-1">
		<a title="newUser" class="btn btn-primary btn-sm " data-toggle="modal" data-target="#new_user">Novo Usuario</a>
	</div>  

	<div id="list" class="row">
		<div class="table-responsive col-md-12">
			<table class="table table-striped" cellspacing="30" cellpadding="30" id="usuarios">
				<thead>
					<tr>
						<th>ID</th>
						<th>Nome</th>
						<th>Email</th>
						<th>Classe</th>
						<th class="actions">Ações</th>
					</tr>
				</thead>
				
				<tbody>

					<?php foreach ( $usuario as $user ) {?>
						<tr>
							<td><?php echo $user->id_usuario; ?></td> 
							<td><?php echo $user->nome_usuario; ?></td>    
							<td><?php echo $user->email_usuario; ?></td>
							<td><?php echo $user->tipo_usuario; ?> </td>
							<td class="actions">
                <a title="Editar" class="btn btn-warning btn-sm fa fa-pencil-square-o"
                    href="<?php echo base_url() . 'usuarios/editar/' . $user->id_usuario; ?>"></a>
                <a title="Deletar" class="btn btn-danger btn-sm fa fa-trash" 
                    href="<?php echo base_url() . 'usuarios/deletar/' . $user->id_usuario; ?>" onclick="return confirm('Confirma a exclusão deste registro?')"></a>
							</td>		

						</tr>	 	 	  	
						  	
				 	<?php } ?>
				</tbody>
			</table>
			 <h4><?php echo $this->session->flashdata('mensagem');?></h4>
        <h4><?php echo $this->session->flashdata('mensagemErro');?></h4>
		</div>
	</div>	

    <div class="row">
      <div class="col-sm-10" >
        <?php echo $pagination; ?>
      </div>
    </div>

</body>

<!-- Modal de inserir cliente-->
<div class="modal fade" id="new_user" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog modal-lg" >
    <div class="modal-content">
      <div class="modal-header  bg-red">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel">Adicionar Usuario</h4>
      </div>
      <div class="modal-body">
       
  <?php echo form_open('usuarios/inserir', 'id="form-pessoas"'); ?>
    
    <form action="" method="post" ENCTYPE="multipart/form-data">
      <div class="row">
        <div class="form-group col-md-5">
            <label for="nome_usuario">Nome</label> 
            <input type="text" class="form-control" id="nome_usuario" name="nome_usuario"
                placeholder="informe o nome" required
                value="<?php echo isset($view_nome_usuario) ? $view_nome_usuario: '' ; ?>">
        </div>     
        <div class="form-group col-md-5">
            <label for="tipo_usuario">tipo</label> 
            <input type="text" class="form-control" id="tipo_usuario" name="tipo_usuario"
                placeholder="informe o tipo" required
                value="<?php echo isset($view_tipo_usuario) ? $view_tipo_usuario: '' ; ?>">
        </div>
    	</div>
    
     <div class="row">
        <div class="form-group col-md-5">
            <label for="email_usuario">Email</label> 
            <input type="text" class="form-control" id="email_usuario" name="email_usuario"
                placeholder="informe emial" required
                value="<?php echo isset($view_email_usuario) ? $view_email_usuario: '' ; ?>">
        </div>
        <div class="form-group col-md-5">
					<label for="password">Senha</label> 
					<input type="text" class="form-control" id="password" name="password"
							placeholder="informe a senha" required 
							value="<?php echo isset($view_password) ? $view_password : '' ; ?>">
        </div>
    	</div>
			<div class="row">
				<div class="col-md-12">
						<input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
								<a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
				</div>

    <?php echo form_close(); ?>

		</div>

      </div>
    </div>
  </div>
</div> <!-- /.modal -->

</html>
